# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# ==============================================================================
# CODE GENERATED BY a2ui_cli. DO NOT EDIT DIRECTLY.
#
# Catalog ID: https://a2ui.org/specification/v0_9/catalogs/basic/catalog.json
#
# This file was automatically generated by the A2UI CLI code generator.
# Any manual modifications will be lost upon regeneration.
# ==============================================================================
# fmt: off
"""Type-safe A2UI builders for basic (version v0.9.1).

AUTO-GENERATED FILE - DO NOT EDIT MANUALLY.
Generated by a2ui_cli.
"""

__a2ui_codegen__ = "a2ui_cli"

from typing import Annotated, Any, Literal, Optional, Sequence
from pydantic import Field

from a2ui.builder.v0_9 import (
    AccessibilityAttributes,
    Action,
    ActionEvent,
    BuilderBaseModel,
    CheckRule,
    Child,
    ChildList,
    ComponentBuilderNode,
    ComponentRef,
    ComponentTree,
    DataBinding,
    DynamicChildList,
    FunctionCall,
    IdAllocator,
    OPEN_ENUM,
    flatten_component_tree,
)


# =============================================================================
# Types & Enums
# =============================================================================
#
# Catalog enums carry OPEN_ENUM metadata: the annotation stays the strict Literal
# for authoring and type checking, and unknown values are only accepted when
# parsing with a lenient validation context.

TextVariant = Annotated[
    Literal["h1", "h2", "h3", "h4", "h5", "caption", "body"], OPEN_ENUM
]
ImageFit = Annotated[
    Literal["contain", "cover", "fill", "none", "scaleDown"], OPEN_ENUM
]
ImageVariant = Annotated[
    Literal[
        "icon", "avatar", "smallFeature", "mediumFeature", "largeFeature", "header",
    ],
    OPEN_ENUM,
]
IconName = Annotated[
    Literal[
        "accountCircle", "add", "arrowBack", "arrowForward", "attachFile",
        "calendarToday", "call", "camera", "check", "close", "delete", "download",
        "edit", "event", "error", "fastForward", "favorite", "favoriteOff", "folder",
        "help", "home", "info", "locationOn", "lock", "lockOpen", "mail", "menu",
        "moreVert", "moreHoriz", "notificationsOff", "notifications", "pause",
        "payment", "person", "phone", "photo", "play", "print", "refresh", "rewind",
        "search", "send", "settings", "share", "shoppingCart", "skipNext",
        "skipPrevious", "star", "starHalf", "starOff", "stop", "upload", "visibility",
        "visibilityOff", "volumeDown", "volumeMute", "volumeOff", "volumeUp", "warning",
    ],
    OPEN_ENUM,
]
FlexJustify = Annotated[
    Literal[
        "start", "center", "end", "spaceBetween", "spaceAround", "spaceEvenly",
        "stretch",
    ],
    OPEN_ENUM,
]
FlexAlign = Annotated[Literal["center", "end", "start", "stretch"], OPEN_ENUM]
ListDirection = Annotated[Literal["vertical", "horizontal"], OPEN_ENUM]
ListAlign = Annotated[Literal["start", "center", "end", "stretch"], OPEN_ENUM]
DividerAxis = Annotated[Literal["horizontal", "vertical"], OPEN_ENUM]
ButtonVariant = Annotated[Literal["default", "primary", "borderless"], OPEN_ENUM]
TextFieldVariant = Annotated[
    Literal["longText", "number", "shortText", "obscured"], OPEN_ENUM
]
ChoicePickerVariant = Annotated[
    Literal["multipleSelection", "mutuallyExclusive"], OPEN_ENUM
]
ChoicePickerDisplayStyle = Annotated[Literal["checkbox", "chips"], OPEN_ENUM]


# =============================================================================
# Item Models
# =============================================================================


class IconNameSvgPath(BuilderBaseModel):
    r"""IconNameSvgPath item model."""

    svg_path: str = Field(alias="svgPath")


class TabItem(BuilderBaseModel):
    r"""An array of objects, where each object defines a tab with a title and a child component."""

    title: str | DataBinding | FunctionCall
    child: Child


class ChoicePickerOption(BuilderBaseModel):
    r"""The list of available options to choose from."""

    label: str | DataBinding | FunctionCall
    value: str


# =============================================================================
# Components
# =============================================================================


class Text(ComponentBuilderNode):
    r"""Text component."""

    component: Literal["Text"] = "Text"
    weight: Optional[float] = None
    text: str | DataBinding | FunctionCall
    variant: Optional[TextVariant] = "body"
    accessibility: Optional[AccessibilityAttributes] = None


class Image(ComponentBuilderNode):
    r"""Image component."""

    component: Literal["Image"] = "Image"
    weight: Optional[float] = None
    url: str | DataBinding | FunctionCall
    description: Optional[str | DataBinding | FunctionCall] = None
    fit: Optional[ImageFit] = "fill"
    variant: Optional[ImageVariant] = "mediumFeature"
    accessibility: Optional[AccessibilityAttributes] = None


class Icon(ComponentBuilderNode):
    r"""Icon component."""

    component: Literal["Icon"] = "Icon"
    weight: Optional[float] = None
    name: IconName | IconNameSvgPath | DataBinding | FunctionCall
    accessibility: Optional[AccessibilityAttributes] = None


class Video(ComponentBuilderNode):
    r"""Video component."""

    component: Literal["Video"] = "Video"
    weight: Optional[float] = None
    url: str | DataBinding | FunctionCall
    accessibility: Optional[AccessibilityAttributes] = None


class AudioPlayer(ComponentBuilderNode):
    r"""AudioPlayer component."""

    component: Literal["AudioPlayer"] = "AudioPlayer"
    weight: Optional[float] = None
    url: str | DataBinding | FunctionCall
    description: Optional[str | DataBinding | FunctionCall] = None
    accessibility: Optional[AccessibilityAttributes] = None


class Row(ComponentBuilderNode):
    r"""A layout component that arranges its children horizontally. To create a grid layout, nest Columns within this Row."""

    component: Literal["Row"] = "Row"
    weight: Optional[float] = None
    children: ChildList
    justify: Optional[FlexJustify] = "start"
    align: Optional[FlexAlign] = "stretch"
    accessibility: Optional[AccessibilityAttributes] = None


class Column(ComponentBuilderNode):
    r"""A layout component that arranges its children vertically. To create a grid layout, nest Rows within this Column."""

    component: Literal["Column"] = "Column"
    weight: Optional[float] = None
    children: ChildList
    justify: Optional[FlexJustify] = "start"
    align: Optional[FlexAlign] = "stretch"
    accessibility: Optional[AccessibilityAttributes] = None


class List(ComponentBuilderNode):
    r"""List component."""

    component: Literal["List"] = "List"
    weight: Optional[float] = None
    children: ChildList
    direction: Optional[ListDirection] = "vertical"
    align: Optional[ListAlign] = "stretch"
    accessibility: Optional[AccessibilityAttributes] = None


class Card(ComponentBuilderNode):
    r"""Card component."""

    component: Literal["Card"] = "Card"
    weight: Optional[float] = None
    child: Child
    accessibility: Optional[AccessibilityAttributes] = None


class Tabs(ComponentBuilderNode):
    r"""Tabs component."""

    component: Literal["Tabs"] = "Tabs"
    weight: Optional[float] = None
    tabs: Sequence[TabItem]
    accessibility: Optional[AccessibilityAttributes] = None


class Modal(ComponentBuilderNode):
    r"""Modal component."""

    component: Literal["Modal"] = "Modal"
    weight: Optional[float] = None
    trigger: Child
    content: Child
    accessibility: Optional[AccessibilityAttributes] = None


class Divider(ComponentBuilderNode):
    r"""Divider component."""

    component: Literal["Divider"] = "Divider"
    weight: Optional[float] = None
    axis: Optional[DividerAxis] = "horizontal"
    accessibility: Optional[AccessibilityAttributes] = None


class Button(ComponentBuilderNode):
    r"""Button component."""

    component: Literal["Button"] = "Button"
    weight: Optional[float] = None
    child: Child
    variant: Optional[ButtonVariant] = "default"
    action: Action
    accessibility: Optional[AccessibilityAttributes] = None
    checks: Optional[Sequence[CheckRule]] = None


class TextField(ComponentBuilderNode):
    r"""TextField component."""

    component: Literal["TextField"] = "TextField"
    weight: Optional[float] = None
    label: str | DataBinding | FunctionCall
    value: Optional[str | DataBinding | FunctionCall] = None
    variant: Optional[TextFieldVariant] = "shortText"
    validation_regexp: Optional[str] = Field(default=None, alias="validationRegexp")
    accessibility: Optional[AccessibilityAttributes] = None
    checks: Optional[Sequence[CheckRule]] = None


class CheckBox(ComponentBuilderNode):
    r"""CheckBox component."""

    component: Literal["CheckBox"] = "CheckBox"
    weight: Optional[float] = None
    label: str | DataBinding | FunctionCall
    value: bool | DataBinding | FunctionCall
    accessibility: Optional[AccessibilityAttributes] = None
    checks: Optional[Sequence[CheckRule]] = None


class ChoicePicker(ComponentBuilderNode):
    r"""A component that allows selecting one or more options from a list."""

    component: Literal["ChoicePicker"] = "ChoicePicker"
    weight: Optional[float] = None
    label: Optional[str | DataBinding | FunctionCall] = None
    variant: Optional[ChoicePickerVariant] = "mutuallyExclusive"
    options: Sequence[ChoicePickerOption]
    value: Sequence[str] | DataBinding | FunctionCall
    display_style: Optional[ChoicePickerDisplayStyle] = Field(
        default="checkbox", alias="displayStyle"
    )
    filterable: Optional[bool] = False
    accessibility: Optional[AccessibilityAttributes] = None
    checks: Optional[Sequence[CheckRule]] = None


class Slider(ComponentBuilderNode):
    r"""Slider component."""

    component: Literal["Slider"] = "Slider"
    weight: Optional[float] = None
    label: Optional[str | DataBinding | FunctionCall] = None
    min: Optional[float] = 0
    max: float
    value: float | DataBinding | FunctionCall
    accessibility: Optional[AccessibilityAttributes] = None
    checks: Optional[Sequence[CheckRule]] = None


class DateTimeInput(ComponentBuilderNode):
    r"""DateTimeInput component."""

    component: Literal["DateTimeInput"] = "DateTimeInput"
    weight: Optional[float] = None
    value: str | DataBinding | FunctionCall
    enable_date: Optional[bool] = Field(default=False, alias="enableDate")
    enable_time: Optional[bool] = Field(default=False, alias="enableTime")
    min: Optional[Any] = None
    max: Optional[Any] = None
    label: Optional[str | DataBinding | FunctionCall] = None
    accessibility: Optional[AccessibilityAttributes] = None
    checks: Optional[Sequence[CheckRule]] = None


# =============================================================================
# Functions & Function Classes
# =============================================================================


class Required(FunctionCall):
    r"""Checks that the value is not null, undefined, or empty."""

    def __init__(self, *, value: Any, **kwargs: Any):
        super().__init__(call="required", args={"value": value}, **kwargs)


class Regex(FunctionCall):
    r"""Checks that the value matches a regular expression string."""

    def __init__(
        self,
        *,
        value: str | DataBinding | FunctionCall,
        pattern: str,
        **kwargs: Any,
    ):
        super().__init__(
            call="regex",
            args={"value": value, "pattern": pattern},
            **kwargs,
        )


class Length(FunctionCall):
    r"""Checks string length constraints."""

    def __init__(
        self,
        *,
        value: str | DataBinding | FunctionCall,
        min: Optional[float] = None,
        max: Optional[float] = None,
        **kwargs: Any,
    ):
        args: dict[str, Any] = {"value": value}
        if min is not None:
            args["min"] = min
        if max is not None:
            args["max"] = max
        super().__init__(call="length", args=args, **kwargs)


class Numeric(FunctionCall):
    r"""Checks numeric range constraints."""

    def __init__(
        self,
        *,
        value: float | DataBinding | FunctionCall,
        min: Optional[float] = None,
        max: Optional[float] = None,
        **kwargs: Any,
    ):
        args: dict[str, Any] = {"value": value}
        if min is not None:
            args["min"] = min
        if max is not None:
            args["max"] = max
        super().__init__(call="numeric", args=args, **kwargs)


class Email(FunctionCall):
    r"""Checks that the value is a valid email address."""

    def __init__(self, *, value: str | DataBinding | FunctionCall, **kwargs: Any):
        super().__init__(call="email", args={"value": value}, **kwargs)


class FormatString(FunctionCall):
    """Performs string interpolation of data model values and other functions in the catalog functions list and returns the resulting string. The value string can contain interpolated expressions in the `${expression}` format. Supported expression types include: JSON Pointer paths to the data model (e.g., `${/absolute/path}` or `${relative/path}`), and client-side function calls (e.g., `${now()}`). Function arguments must be named (e.g., `${formatDate(value:${/currentDate}, format:'MM-dd')}`). To include a literal `${` sequence, escape it as `\\${`."""

    def __init__(self, *, value: str | DataBinding | FunctionCall, **kwargs: Any):
        super().__init__(call="formatString", args={"value": value}, **kwargs)


class FormatNumber(FunctionCall):
    r"""Formats a number with the specified grouping and decimal precision."""

    def __init__(
        self,
        *,
        value: float | DataBinding | FunctionCall,
        decimals: Optional[float | DataBinding | FunctionCall] = None,
        grouping: Optional[bool | DataBinding | FunctionCall] = None,
        **kwargs: Any,
    ):
        args: dict[str, Any] = {"value": value}
        if decimals is not None:
            args["decimals"] = decimals
        if grouping is not None:
            args["grouping"] = grouping
        super().__init__(call="formatNumber", args=args, **kwargs)


class FormatCurrency(FunctionCall):
    r"""Formats a number as a currency string."""

    def __init__(
        self,
        *,
        value: float | DataBinding | FunctionCall,
        currency: str | DataBinding | FunctionCall,
        decimals: Optional[float | DataBinding | FunctionCall] = None,
        grouping: Optional[bool | DataBinding | FunctionCall] = None,
        **kwargs: Any,
    ):
        args: dict[str, Any] = {"value": value, "currency": currency}
        if decimals is not None:
            args["decimals"] = decimals
        if grouping is not None:
            args["grouping"] = grouping
        super().__init__(call="formatCurrency", args=args, **kwargs)


class FormatDate(FunctionCall):
    r"""Formats a timestamp into a string using a pattern."""

    def __init__(
        self,
        *,
        value: Any | DataBinding | FunctionCall,
        format: str | DataBinding | FunctionCall,
        **kwargs: Any,
    ):
        super().__init__(
            call="formatDate",
            args={"value": value, "format": format},
            **kwargs,
        )


class Pluralize(FunctionCall):
    r"""Returns a localized string based on the Common Locale Data Repository (CLDR) plural category of the count (zero, one, two, few, many, other). Requires an 'other' fallback. For English, just use 'one' and 'other'."""

    def __init__(
        self,
        *,
        value: float | DataBinding | FunctionCall,
        zero: Optional[str | DataBinding | FunctionCall] = None,
        one: Optional[str | DataBinding | FunctionCall] = None,
        two: Optional[str | DataBinding | FunctionCall] = None,
        few: Optional[str | DataBinding | FunctionCall] = None,
        many: Optional[str | DataBinding | FunctionCall] = None,
        other: str | DataBinding | FunctionCall,
        **kwargs: Any,
    ):
        args: dict[str, Any] = {"value": value, "other": other}
        if zero is not None:
            args["zero"] = zero
        if one is not None:
            args["one"] = one
        if two is not None:
            args["two"] = two
        if few is not None:
            args["few"] = few
        if many is not None:
            args["many"] = many
        super().__init__(call="pluralize", args=args, **kwargs)


class OpenUrl(FunctionCall):
    r"""Opens the specified URL in a browser or handler. This function has no return value."""

    def __init__(self, *, url: str, **kwargs: Any):
        super().__init__(call="openUrl", args={"url": url}, **kwargs)


class And(FunctionCall):
    r"""Performs a logical AND operation on a list of boolean values."""

    def __init__(
        self,
        *,
        values: Sequence[bool | DataBinding | FunctionCall],
        **kwargs: Any,
    ):
        super().__init__(call="and", args={"values": values}, **kwargs)


class Or(FunctionCall):
    r"""Performs a logical OR operation on a list of boolean values."""

    def __init__(
        self,
        *,
        values: Sequence[bool | DataBinding | FunctionCall],
        **kwargs: Any,
    ):
        super().__init__(call="or", args={"values": values}, **kwargs)


class Not(FunctionCall):
    r"""Performs a logical NOT operation on a boolean value."""

    def __init__(self, *, value: bool | DataBinding | FunctionCall, **kwargs: Any):
        super().__init__(call="not", args={"value": value}, **kwargs)


# =============================================================================
# Exports
# =============================================================================

__all__ = [
    "TextVariant",
    "ImageFit",
    "ImageVariant",
    "IconName",
    "FlexJustify",
    "FlexAlign",
    "ListDirection",
    "ListAlign",
    "DividerAxis",
    "ButtonVariant",
    "TextFieldVariant",
    "ChoicePickerVariant",
    "ChoicePickerDisplayStyle",
    "IconNameSvgPath",
    "TabItem",
    "ChoicePickerOption",
    "Text",
    "Image",
    "Icon",
    "Video",
    "AudioPlayer",
    "Row",
    "Column",
    "List",
    "Card",
    "Tabs",
    "Modal",
    "Divider",
    "Button",
    "TextField",
    "CheckBox",
    "ChoicePicker",
    "Slider",
    "DateTimeInput",
    "Required",
    "Regex",
    "Length",
    "Numeric",
    "Email",
    "FormatString",
    "FormatNumber",
    "FormatCurrency",
    "FormatDate",
    "Pluralize",
    "OpenUrl",
    "And",
    "Or",
    "Not",
    "AccessibilityAttributes",
    "Action",
    "ActionEvent",
    "BuilderBaseModel",
    "CheckRule",
    "Child",
    "ChildList",
    "ComponentBuilderNode",
    "ComponentRef",
    "ComponentTree",
    "DataBinding",
    "DynamicChildList",
    "FunctionCall",
    "IdAllocator",
    "flatten_component_tree",
]
