# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# ==============================================================================
# CODE GENERATED BY a2ui_cli. DO NOT EDIT DIRECTLY.
#
# Catalog ID: enums_catalog
#
# This file was automatically generated by the A2UI CLI code generator.
# Any manual modifications will be lost upon regeneration.
# ==============================================================================
# fmt: off
"""Type-safe A2UI builders for enums_catalog (version v0.9.1).

AUTO-GENERATED FILE - DO NOT EDIT MANUALLY.
Generated by a2ui_cli.
"""

__a2ui_codegen__ = "a2ui_cli"

from typing import Annotated, Literal

from a2ui.builder.v0_9 import (
    AccessibilityAttributes,
    Action,
    ActionEvent,
    BuilderBaseModel,
    CheckRule,
    Child,
    ChildList,
    ComponentBuilderNode,
    ComponentRef,
    ComponentTree,
    DataBinding,
    DynamicChildList,
    FunctionCall,
    IdAllocator,
    OPEN_ENUM,
    flatten_component_tree,
)


# =============================================================================
# Types & Enums
# =============================================================================
#
# Catalog enums carry OPEN_ENUM metadata: the annotation stays the strict Literal
# for authoring and type checking, and unknown values are only accepted when
# parsing with a lenient validation context.

StatusBadgeStatus = Annotated[Literal["draft", "published", "archived"], OPEN_ENUM]


# =============================================================================
# Components
# =============================================================================


class StatusBadge(ComponentBuilderNode):
    r"""StatusBadge component."""

    component: Literal["StatusBadge"] = "StatusBadge"
    label: str
    status: StatusBadgeStatus


# =============================================================================
# Exports
# =============================================================================

__all__ = [
    "StatusBadgeStatus",
    "StatusBadge",
    "AccessibilityAttributes",
    "Action",
    "ActionEvent",
    "BuilderBaseModel",
    "CheckRule",
    "Child",
    "ChildList",
    "ComponentBuilderNode",
    "ComponentRef",
    "ComponentTree",
    "DataBinding",
    "DynamicChildList",
    "FunctionCall",
    "IdAllocator",
    "flatten_component_tree",
]
